on :
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"

    pull_request:
        branches:
            - main
            - "release/**"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@4.2.2

            - name: run tests
              run: npm test